spring.application.name=BetCaseStudy
spring.docker.compose.enabled=false

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.password=
shedlock.redis.key-prefix=shedlock

betcasestudy.broadcast.page-size=100

betcasestudy.betslip.max-multiplier=500
betcasestudy.betslip.timeout-ms=2000
betcasestudy.betslip.max-total-investment=10000